Process 19823: Initializing TITAN model...

===== FOLD 1/5 =====
/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
--- Epoch 1/30 ---
Train:   7%|█████████████████▋                                                                                                                                                                                                                                            | 9/129 [00:01<00:14,  8.39it/s]

[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0


[调试信息] 捕获到异常: too many indices for tensor of dimension 0
  File "/home/aletolia/documents/CPath/Fate/main.py", line 200, in <module>
    main()
  File "/home/aletolia/documents/CPath/Fate/main.py", line 191, in main
    cross_validation_loop(
  File "/home/aletolia/documents/CPath/Fate/main.py", line 86, in cross_validation_loop
    train_metrics, train_errors = run_epoch(model, train_loader, device, flags, optimizer, task_criteria, dwa_keeper)
  File "/home/aletolia/documents/CPath/Fate/trainer.py", line 46, in run_epoch
    model_output = model(
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aletolia/documents/CPath/Fate/model.py", line 144, in forward
    expert_output = self.post_fusion_moe(task_attended_feature, task_id=t)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aletolia/documents/CPath/Fate/MoE.py", line 107, in forward
    active_expert_indices = torch.cat([task_expert_indices, generalist_indices]).unique()
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_tensor.py", line 938, in unique
    return torch.unique(
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_jit_internal.py", line 497, in fn
    return if_false(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_jit_internal.py", line 497, in fn
    return if_false(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/functional.py", line 996, in _return_output
    output, _, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/functional.py", line 910, in _unique_impl
    output, inverse_indices, counts = torch._unique2(
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/aletolia/documents/CPath/Fate/main.py", line 200, in <module>
    main()
  File "/home/aletolia/documents/CPath/Fate/main.py", line 191, in main
    cross_validation_loop(
  File "/home/aletolia/documents/CPath/Fate/main.py", line 86, in cross_validation_loop
    train_metrics, train_errors = run_epoch(model, train_loader, device, flags, optimizer, task_criteria, dwa_keeper)
  File "/home/aletolia/documents/CPath/Fate/trainer.py", line 46, in run_epoch
    model_output = model(
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aletolia/documents/CPath/Fate/model.py", line 144, in forward
    expert_output = self.post_fusion_moe(task_attended_feature, task_id=t)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aletolia/documents/CPath/Fate/MoE.py", line 107, in forward
    active_expert_indices = torch.cat([task_expert_indices, generalist_indices]).unique()
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_tensor.py", line 938, in unique
    return torch.unique(
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_jit_internal.py", line 497, in fn
    return if_false(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_jit_internal.py", line 497, in fn
    return if_false(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/functional.py", line 996, in _return_output
    output, _, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/functional.py", line 910, in _unique_impl
    output, inverse_indices, counts = torch._unique2(
KeyboardInterrupt
