Process 16566: Initializing TITAN model...

===== FOLD 1/5 =====
/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
--- Epoch 1/30 ---
Train:  15%|█████████████████████████████████████▎                                                                                                                                                                                                                       | 19/129 [00:02<00:09, 11.44it/s]Exception in thread Thread-4 (_pin_memory_loop):
Traceback (most recent call last):
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 54, in _pin_memory_loop
    do_one_step()
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 31, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 495, in rebuild_storage_fd
    fd = df.detach()
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):                                                                                                                                                                                                                                                                        
  File "/home/aletolia/documents/CPath/Fate/main.py", line 200, in <module>
    main()
  File "/home/aletolia/documents/CPath/Fate/main.py", line 191, in main
    cross_validation_loop(
  File "/home/aletolia/documents/CPath/Fate/main.py", line 86, in cross_validation_loop
    train_metrics, train_errors = run_epoch(model, train_loader, device, flags, optimizer, task_criteria, dwa_keeper)
  File "/home/aletolia/documents/CPath/Fate/trainer.py", line 46, in run_epoch
    model_output = model(
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aletolia/documents/CPath/Fate/model.py", line 144, in forward
    expert_output = self.post_fusion_moe(task_attended_feature, task_id=t)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aletolia/documents/CPath/Fate/MoE.py", line 107, in forward
    active_expert_indices = torch.cat([task_expert_indices, generalist_indices]).unique()
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_tensor.py", line 938, in unique
    return torch.unique(
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_jit_internal.py", line 497, in fn
    return if_false(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_jit_internal.py", line 497, in fn
    return if_false(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/functional.py", line 996, in _return_output
    output, _, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/functional.py", line 910, in _unique_impl
    output, inverse_indices, counts = torch._unique2(
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/aletolia/documents/CPath/Fate/main.py", line 200, in <module>
    main()
  File "/home/aletolia/documents/CPath/Fate/main.py", line 191, in main
    cross_validation_loop(
  File "/home/aletolia/documents/CPath/Fate/main.py", line 86, in cross_validation_loop
    train_metrics, train_errors = run_epoch(model, train_loader, device, flags, optimizer, task_criteria, dwa_keeper)
  File "/home/aletolia/documents/CPath/Fate/trainer.py", line 46, in run_epoch
    model_output = model(
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aletolia/documents/CPath/Fate/model.py", line 144, in forward
    expert_output = self.post_fusion_moe(task_attended_feature, task_id=t)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aletolia/documents/CPath/Fate/MoE.py", line 107, in forward
    active_expert_indices = torch.cat([task_expert_indices, generalist_indices]).unique()
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_tensor.py", line 938, in unique
    return torch.unique(
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_jit_internal.py", line 497, in fn
    return if_false(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/_jit_internal.py", line 497, in fn
    return if_false(*args, **kwargs)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/functional.py", line 996, in _return_output
    output, _, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/home/aletolia/anaconda3/envs/fate/lib/python3.10/site-packages/torch/functional.py", line 910, in _unique_impl
    output, inverse_indices, counts = torch._unique2(
KeyboardInterrupt
